
package es.meh.catastro;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Atributos", targetNamespace = "http://www.catastro.meh.es/")
public class IOVCConsultaObtenerConsultaVdRErrorFaultFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Atributos faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IOVCConsultaObtenerConsultaVdRErrorFaultFaultFaultMessage(String message, Atributos faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IOVCConsultaObtenerConsultaVdRErrorFaultFaultFaultMessage(String message, Atributos faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.meh.catastro.Atributos
     */
    public Atributos getFaultInfo() {
        return faultInfo;
    }

}
